### PR TITLE
Drag and drop a tar.gz over the app to import it

### LINKED ISSUE #69: Drag and drop a tar.gz over the app to import it
**Is your feature request related to a problem? Please describe.**
I was importing a tar.gz and I mechanically dragged it over Docker Desktop (the extension being open) and realise that it is not possible

**Describe the solution you'd like**
When dropping a file on the app I wish the import dialog opens

**Describe alternatives you've considered**
none, just click on the button and navigate to the folder where my tar.gs is.

**Additional context**

### PR DESCRIPTION
**Pull request by eigengravy**
Closes #69

### CODE REVIEW

**Comment by eigengravy** [comment]
@benja-M-1 Currently detects .tar.gz, .tar.zst and .tar.bz2 being dropped and opens the normal ImportDialog, however it doesn't currently load the dropped file into the local file field. how should i go about implementing that? from what i gather, i have to extend the AppContext to include a setFile action.

**Comment by benja-M-1** [comment]
Hi @eigengravy it looks promising!

> i have to extend the AppContext to include a setFile action.

What do you mean by AppContext?

> how should i go about implementing that?
I don't know I thought some libraries would do it. I think @felipecruz91 gave it a try and didn't managed to get the file path.

**Comment by eigengravy** [comment]
Yeah, I was not able to get the file path. I plan to look into it more.
https://github.com/docker/volumes-backup-extension/blob/915c5754ab43d6897690c5bb7d8a7640636cb211/ui/src/index.tsx#L11-L18  
If I do figure it out, I would have to extend the above right?

**Comment by benja-M-1** [comment]
@eigengravy I think @lucbpz might have better knowledge than me on this question :)

**Comment by benja-M-1** [comment]
Arf, well, in this case, I don't think we should do anything when dropping a file in the extension. I fear it will be misleading. Users will think there is a bug because it doesn't fill the file path. They might even try again thinking something might gone wrong and have to select it with the file picker in the end, which will add more frustration and making things even worse

@felipecruz91 WDYT?

In any case, thanks @eigengravy for spending some time on that. We really appreciate that :)

**Comment by eigengravy** [comment]
Should I add a notification that dragging and dropping files is not supported?

**Comment by felipecruz91** [comment]
Given that as of today it doesn't seem possible to get the absolute host path of the file imported when dragging it from the host to the extension view, I'm closing this PR.

Thank you @eigengravy for your time and effort in investigating this.

**Pull request closed without merging**
